"""ARC v4 Step 2: rebuild action loss matrix with v4 grounded risk + v4 features.

Same loss formulation as v3:
    loss(x, a) = α · (1 - correct) + β · risk + λ · cost
    α=1.0, β=1.0, λ=0.05

Inputs:
  - v1 unified action tables (correctness, costs, scalar signals)
  - v4 risk labels at /risk/{bench}_risk.json (regenerated by risk_*_v4 scripts)
  - v4 dense features at /unified_v4/{bench}_features.npz

Output: /unified_v4/{bench}_loss_matrix.json   (per-sample reward vector + features)
"""
import json, os
import numpy as np

V1_DIR  = "./data/unified"
RISK_DIR = "./data/risk"
DST     = "./data/unified_v4"
BENCHES = ['POPE', 'HallusionBench', 'A-OKVQA', 'FEVER']
ACTIONS = ['answer_direct', 'recover_then_answer', 'escalate_to_stronger_model', 'abstain']

ALPHA, BETA, LAMBDA = 1.0, 1.0, 0.05
COST = {'answer_direct': 1.0, 'recover_then_answer': 2.0,
        'escalate_to_stronger_model': 2.3, 'abstain': 0.0}


def loss_of(correct, risk, cost):
    return ALPHA * (1 - correct) + BETA * risk + LAMBDA * cost


def main():
    os.makedirs(DST, exist_ok=True)
    summary = {}
    for bench in BENCHES:
        risk_path = os.path.join(RISK_DIR, f'{bench}_risk.json')
        if not os.path.exists(risk_path):
            print(f'[skip] {bench}: risk_v4 not yet generated')
            continue
        rows = json.load(open(os.path.join(V1_DIR, f'{bench}_action_table.json')))
        risk_map = json.load(open(risk_path))
        out_rows = []
        bucket = {a: [0, 0, 0, 0] for a in ('answer_direct', 'recover_then_answer', 'escalate_to_stronger_model')}
        for r in rows:
            sid = r['sample_id']
            risk_per_action = risk_map.get(sid, {})
            sample = {
                'sample_id': sid, 'benchmark': r['benchmark'],
                'category': r.get('category'), 'gt': r.get('gt'),
                'actions': {},
            }
            for a in ACTIONS:
                if a == 'abstain':
                    correct, risk_val, cost = 0, 0.0, 0.0
                    L = loss_of(correct, risk_val, cost)
                    sample['actions'][a] = {
                        'answer': None, 'correct': correct,
                        'risk': risk_val, 'cost': cost,
                        'loss': L, 'reward': -L,
                    }
                else:
                    src = r[a]
                    correct = int(src['correct'])
                    cost = COST[a]
                    re = risk_per_action.get(a, {})
                    risk_val = float(re.get('risk_score', 0.0))
                    L = loss_of(correct, risk_val, cost)
                    sample['actions'][a] = {
                        'answer': src.get('answer'),
                        'correct': correct,
                        'risk': risk_val,
                        'risk_label': re.get('risk_label') or re.get('judge_label'),
                        'prop_type':  re.get('prop_type'),
                        'cost': cost,
                        'loss': L,
                        'reward': -L,
                        'confidence_margin': src.get('confidence_margin', 0.0),
                        'seq_logprob':       src.get('seq_logprob', 0.0),
                    }
                    bin_idx = (1 - correct) * 2 + (1 if risk_val > 0 else 0)
                    bucket[a][bin_idx] += 1
            out_rows.append(sample)
        json.dump({'bench': bench, 'n': len(out_rows),
                   'alpha': ALPHA, 'beta': BETA, 'lambda': LAMBDA,
                   'rows': out_rows},
                  open(os.path.join(DST, f'{bench}_loss_matrix.json'), 'w'))

        # Independence stats
        act_stats = {}
        for a in ('answer_direct', 'recover_then_answer', 'escalate_to_stronger_model'):
            cor = np.array([s['actions'][a]['correct'] for s in out_rows])
            risk_v = np.array([s['actions'][a]['risk'] for s in out_rows])
            wrong = 1 - cor
            if risk_v.std() > 1e-6 and wrong.std() > 1e-6:
                rho = float(np.corrcoef(risk_v, wrong)[0, 1])
            else:
                rho = float('nan')
            act_stats[a] = {
                'wrong_rate': float(wrong.mean()),
                'mean_risk': float(risk_v.mean()),
                'high_risk_rate': float((risk_v > 0.5).mean()),
                'corr_risk_wrong': rho,
                'buckets': bucket[a],
            }
        summary[bench] = {'n': len(out_rows), 'per_action': act_stats}

    json.dump(summary, open(os.path.join(DST, 'loss_summary.json'), 'w'), indent=2)

    print(f"\n{'='*108}")
    print(f"v4 loss matrix: loss = {ALPHA}·(1-correct) + {BETA}·risk + {LAMBDA}·cost")
    print('=' * 108)
    print(f"{'bench':<17} {'action':<32} {'wrong':<8} {'mean_risk':<10} {'high_risk':<10} {'corr(risk,wrong)':<18} {'buckets':<22}")
    for b, s in summary.items():
        for a, st in s['per_action'].items():
            bk = st['buckets']
            print(f"{b:<17} {a:<32} {st['wrong_rate']*100:>5.2f}%  "
                  f"{st['mean_risk']:>7.3f}    {st['high_risk_rate']*100:>6.2f}%    "
                  f"{st['corr_risk_wrong']:>+10.3f}        "
                  f"{bk[0]:>4d}/{bk[1]:>3d}/{bk[2]:>3d}/{bk[3]:>3d}")
        print()


if __name__ == '__main__':
    main()
